### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -vto see invocation)

### ISSUE THREAD

**Issue by Vincent-St** [Kapeli/Dash-iOS#11]
<img width="892" alt="screen shot 2016-11-15 at 10 34 46 pm" src="https://cloud.githubusercontent.com/assets/12606544/20309641/c2aee8de-ab83-11e6-9ab9-414cba164f39.png">

**Comment by slangley** [comment]
Use the xcworkspace to build instead of the xcproject?  

This usually happens when using Cocoapods and you are building from the xcproject which doesn't know about the cocoapod libraries.

**Comment by Vincent-St** [comment]
Thanks, slangley. I'm new to Swift. Don't know to how to use the xcworkspace to build instead of the xcproject. Any suggestion you can share with me?

**Comment by nadia-am** [comment]
I am using xcworkspace file but error still remind, do you know how to solve it?

**Comment by xgchen516** [comment]
> Use the xcworkspace to build instead of the xcproject?
> 
> This usually happens when using Cocoapods and you are building from the xcproject which doesn't know about the cocoapod libraries.

Thank you so much!!!

**Comment by ksmkr** [comment]
There is no . xcworkspace file in my projects iOS folder.please tell me how to resolve this

**Comment by esthicodes** [comment]
What does it mean to work the terminal and what to do if it does not compile?

**Comment by AhmedRajib** [comment]
get any solution ? my project worked on Intel base mac but didn't work on M1 chip ,  i open xcworkspace but still now same issue.

**Comment by saurabhkanswal** [comment]
> get any solution ? my project worked on Intel base mac but didn't work on M1 chip , i open xcworkspace but still now same issue.

same issue is happening for me in mac m1
did you get the soluntion?

**Comment by sam20042004** [comment]
hey, i got this error while executing very first code in vscode in mac m1
can you tell me what should i do

<img width="1440" alt="Screenshot 2022-02-01 at 2 49 14 AM" src="https://user-images.githubusercontent.com/98780386/151875185-4eba9fec-06d7-470d-8875-012f41c78c54.png">

**Comment by miltoncassul** [comment]
I have the same problem on vscode mac intel, could someone help me solve it?

**Comment by Dhi-2004** [comment]
I am facing the exact same issue. It would be great if some one could give me a solution
