### ISSUE TITLE
Downloadable resources for Ipad 

### ISSUE THREAD

**Issue by davidWilliams96080** [Kapeli/Dash-iOS#112]
Would like to see support for downloading resources for Dash on the IPad that would not require Airdropping or having to use iTunes File Sharing - more specifically Apple APIs.

Using iTunes File Sharing yields nothing (no files to share) so I can’t add resource files to Dash on iPad

**Comment by davidWilliams96080** [comment]
Love the app otherwise.

**Comment by Kapeli** [comment]
Apple does not allow me to redistribute their docs, so this is not currently possible. The only way to currently get the docs is from Xcode.app.
