### ISSUE TITLE
what is name Dash in IOS or IpadOS in china region?

### ISSUE THREAD

**Issue by sundongwei** [Kapeli/Dash-iOS#134]
i searched in app store , but not found it ~? CHINA REGION.

**Comment by RockyZ** [comment]
Not found from HONGKONG and US Region. It may be removed from AppStore already.

**Comment by mountainash** [comment]
Also gone in Australia. I'm guessing it's been removed universally. @sundongwei Issue can be closed.

<img width="372" alt="Screen Shot: This app is currently not available in your country or region." src="https://user-images.githubusercontent.com/27637/180706293-ded993a1-32f2-44b8-8f57-e08dc15c6c04.png">

**Comment by sundongwei** [comment]
> Also gone in Australia. I'm guessing it's been removed universally. @sundongwei Issue can be closed.
> 
> <img alt="Screen Shot: This app is currently not available in your country or region." width="372" src="https://user-images.githubusercontent.com/27637/180706293-ded993a1-32f2-44b8-8f57-e08dc15c6c04.png">

thanks
