### ISSUE TITLE
Is it possible to compile Dash-iOS for iOS 7.1.2?

### ISSUE THREAD

**Issue by hamid914** [Kapeli/Dash-iOS#15]
I tried to compile on Xcode 8.0 with manually added 7.1 iPhoneOS platform. It compiles with this warning:
`ld: warning: object file (~/Library/Developer/Xcode/DerivedData/Dash_iOS-quiemwexbwwcvhvpnwbvzmgqlnpr/Build/Products/Debug-iphoneos/libPods-Dash.a(Pods-Dash-dummy.o)) was built for newer iOS version (9.0) than being linked (7.1)`
I changed this line in `Podfile`:
`platform :ios, "7.1"`
and `IPHONEOS_DEPLOYMENT_TARGET` in Pods project; but no luck.
The code compiles and runs on my iPhone 4, but its screen freezes in the first screen and there are no reactions.
Is it possible to configure the project to be compiled for iOS 7.1.2?

**Comment by puttin** [comment]
try modify this line https://github.com/Kapeli/Dash-iOS/blob/be3fc678a77a4f45ec01bbf3f59d3a4d51c2d5f5/Dash/DHAppDelegate.m#L224
with mainScreen.bounds

**Comment by Kapeli** [comment]
This is not possible, sorry. Even if you got it to compile it would most likely crash sooner or later.
