### ISSUE TITLE
Please add to docs: requires Xcode 8 and Sierra / 10.12 to build.

### ISSUE THREAD

**Issue by theconsultant** [Kapeli/Dash-iOS#2]

**Comment by mcomisso** [comment]
Works fine here with
El Capitan 10.11.6 (15G1108) + Xcode 8.1

👍

**Comment by teslamint** [comment]
Works fine with
Sierra 10.12.2 (16C41b) + Xcode 8.1

**Comment by Kapeli** [comment]
@theconsultant What are you using and what error are you getting?

**Comment by almatri** [comment]
Not wirking on xcode 7
