### ISSUE TITLE
Downloaded Cheat Sheets are not displayed in the Docsets' table view

### ISSUE THREAD

**Issue by yoha** [Kapeli/Dash-iOS#24]
I have successfully downloaded several cheat sheets but they are not listed on the main table view. You can see below:

[Screenshot of the Cheat Sheets table view](http://i.imgur.com/01xa74S.png)
[Screenshot of the main table view](http://i.imgur.com/p4T4DgL.png)

Specs:
iPad Mini 1st. gen. running iOS 9.3.5

Do you receive reports of the same anomaly?

**Comment by Kapeli** [comment]
Do user contributed docsets work?

**Comment by jormungand** [comment]
iOS 10.1.1 -- same

Cheatsheets and User Contributed docsets behave the same way:
* you download item1 --> you see it on main table
* you download item2 --> now you see only item2 (on main table)
* you delete either item --> it disappears from main table

it looks like the only one item of the type

**Comment by yoha** [comment]
My observation after playing around to find this particular anomaly pattern is that the main table can only list *one* docset in spite of having installed several docsets.

**Comment by Kapeli** [comment]
Thanks for letting me know about this!
