### ISSUE TITLE
Font Resizing Controls do not work on iPad(s)

### ISSUE THREAD

**Issue by leoofborg** [Kapeli/Dash-iOS#25]
It seems that Font Resize controls do not work on any iPad (Mini, Air2, Pro). iPhone 6 Plus? Fine.

1. Open a docset or cheatsheet
2. Try the Font Size Controls

RESULT: Controls show as being invoked/called in XCode Console, but no effect in UI. No change in font size at all.

REGRESS: Try above steps with iPhone. Works as expected.

**Comment by Kapeli** [comment]
This is a known bug in iOS 10. See https://forums.developer.apple.com/thread/51079 for more info.

It seems to be fixed in iOS 10.2.

As there's no way to fix this bug right now I'm going to close it. It should fix itself when iOS 10.2 is released.

**Comment by leoofborg** [comment]
Sorry and thank you, Bogdan… I didn’t know about this iOS bug.

I’ll keep writing bugs as I find them. Sorry for any that aren’t yours. 

-Leo

**Comment by Kapeli** [comment]
No need for sorries. Please report all bugs you encounter.
