### ISSUE TITLE
(Jump to) Main Page Control missing on iPad(s)

### ISSUE THREAD

**Issue by leoofborg** [Kapeli/Dash-iOS#27]
PROBLEM: The main page '>' control that appears at the top of every docset is missing when Dash-iOS is run on an iPad.

0. Grab current Dash (12/3/2016, post 1.6 build) and sideload.
1. Run on iPhone. Open Bash (or other docset). Note "Bash >" that allows jump to main page.
2. Run on iPad. Open Bash (or other docset). Note "Bash" but not jump control to or back to main page. If you "drill in" there's no control. 

EXPECT: Same control as iPhone, whether in landscape or (as I run on my iPads) portrait. I'm 100% in portrait mode most of the time.

**Comment by Kapeli** [comment]
This isn't needed on the iPad, as the iPad version loads the index page directly when you open a docset.
