### ISSUE TITLE
Possible to build without removing installed docsets?

### ISSUE THREAD

**Issue by kleerkoat** [Kapeli/Dash-iOS#29]
i'm guessing it's not possible but i thought i'd ask. thank you.

**Comment by Kapeli** [comment]
What do you mean? Docsets are preserved between runs. Please provide step-by-step instructions on how to replicate the issue.

**Comment by kleerkoat** [comment]
not sure what i did differently this time but it seems to have saved my transferred docsets this time.

sorry for false alarm.
