### ISSUE TITLE
Can see iPad Dash, but "Pair Remote" from OS X does nothing?

### ISSUE THREAD

**Issue by rud-bookbites** [Kapeli/Dash-iOS#31]
OS X 10.12.2, Dash 3.4.2, Dash iOS 1.6.0. 

Dunno if this may be a code-signing problem or something else. Just got the 1.6.0 iOS version installed. Anything I can try to debug the issue? Is this a defunct feature now that the iOS client is open sourced? Just seems like a cool feature is all.

**Comment by Kapeli** [comment]
The iOS remote should work.

Check the console logs for both iOS and macOS to figure out what happens.

**Comment by rud-bookbites** [comment]
I'll have a look tonight, thank you for the quick feedback.

**Comment by Kapeli** [comment]
Any news?

**Comment by rud-bookbites** [comment]
It's been crazy times, not sure when I'll get around to this. I'll take your word it works for others and close this one out, no need to have an open ticket because I haven't gotten back to you. Thank you for following up :)

**Comment by rud-bookbites** [comment]
*hmmm*

Just re-tried on my current machine. In the OS X log I see:
```
default	11:11:32.009520 +0100	Dash	sent pairRequest
<snip: opendirectoryd stuff>
default	11:11:46.841357 +0100	Dash	UNIX error exception: 17
default	11:11:46.841474 +0100	Dash	0x618000e75600 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	11:11:46.841546 +0100	Dash	0x618000e75600 closed /private/var/db/mds/system/mdsDirectory.db
default	11:11:46.841674 +0100	Dash	0x618000e757c0 opened /Users/rud/Library/Keychains/login.keychain-db: 585760 bytes
default	11:11:46.841901 +0100	Dash	0x618000e757c0 closed /Users/rud/Library/Keychains/login.keychain-db
default	11:11:46.843250 +0100	Dash	loading /Users/rud/Library/Keychains/login.keychain-db
default	11:11:46.845375 +0100	Dash	0x618000e68240 opened /Library/Keychains/System.keychain: 64004 bytes
default	11:11:46.845437 +0100	Dash	0x618000e68240 closed /Library/Keychains/System.keychain
default	11:11:46.846409 +0100	Dash	loading /Library/Keychains/System.keychain
default	11:11:46.848725 +0100	Dash	TIC TCP Conn Start [276:0x61000019cb10]
default	11:11:46.989134 +0100	Dash	TIC TCP Conn Event [276:0x61000019cb10]: 1 Err(0)
default	11:11:46.989178 +0100	Dash	TIC TCP Conn Connected [276:0x61000019cb10]: Err(0)
default	11:11:46.989322 +0100	Dash	TIC Enabling TLS [276:0x61000019cb10]
default	11:11:47.116492 +0100	Dash	TIC TLS Event [276:0x61000019cb10]: 2, Pending(0)
default	11:11:47.116585 +0100	Dash	TIC TLS Event [276:0x61000019cb10]: 11, Pending(0)
default	11:11:47.116942 +0100	Dash	TIC TLS Event [276:0x61000019cb10]: 22, Pending(0)
default	11:11:47.117060 +0100	Dash	TIC TLS Event [276:0x61000019cb10]: 12, Pending(0)
default	11:11:47.117133 +0100	Dash	TIC TLS Event [276:0x61000019cb10]: 14, Pending(0)
```

**Comment by rud-bookbites** [comment]
Ah, fixed it by making the iPad sleep and wake again, then the pairing dialog appeared. Strange, but works no.

**Comment by ErebusBat** [comment]
This seems to duplicate #34  (x-linking for future people).

I was also having this problem.  Looking at the XCode logs of a _successful_ pairing attempt I see:

```
2017-01-31 08:53:46.050479 Dash[267:5829] [MC] Reading from public effective user settings.
2017-01-31 08:53:46.900513 Dash[267:5829] Accepting IPv4 connection from 192.168.0.100 on port 51313
2017-01-31 08:53:46.900931 Dash[267:5829] My name: Andrew’s iPhone port: 49550
```

What is interesting is that on previous unsuccessful attempts I did _not_ get the last two lines indicating that Dash iOS was listening.  I was able to "fix" this by rebooting my phone and then the pairing request succeeded.

I don't know why it couldn't start the server (nothing was logged), but hopefully that helps other people.

**Comment by Lumus** [comment]
I hope this doesn't come across as rude as I have no intention for it to be. I wanted to ask why is this ticket (and also #34) closed if the problem hasn't actually been fixed? Or has it been and the update hasn't been pushed out?

**Comment by Kapeli** [comment]
@Lumus have you tried rebooting your iPad/iPhone?

The issues are closed because the initiators closed them, as they were able to solve the problem by rebooting their devices (or similar steps).

I have no idea what causes the issue and whether or not the cause is on my end or Apple's.

**Comment by davidbaraff** [comment]
I am unable to pair over bluetooth.  (My mac I need to use this with is not on wifi.)  This used to work, but that was like a year ago.

**Comment by davidbaraff** [comment]
I get the part where it says I should enter some text on my iPad (i.e. that message comes up on my mac) but when I click the button, my iPad never prompts me to enter that text.

**Comment by Kapeli** [comment]
@davidbaraff Please try [v1.6.2](https://github.com/Kapeli/Dash-iOS/releases). It should fix this issue.

**Comment by davidbaraff** [comment]
I.e. build myself, and not load from the app store?

**Comment by Kapeli** [comment]
Yes, or wait for v1.6.2 to be released on the App Store (it's waiting for review).

**Comment by davidbaraff** [comment]
Beautiful.  Worked like a charm (built and installed from XCode).


Maybe it doesn’t matter, but although this is version 1.6.2, I noted that the version number listed for both targets (Dash and Dash App Store) still says 1.6.1?

**Comment by Kapeli** [comment]
Oops. I forgot to commit the version bump. I'll fix that.

**Comment by rud-bookbites** [comment]
Just downloaded 1.6.1 from the app-store, I can now successfully pair. Yay!
