### ISSUE TITLE
Is it possible to download Apple docs directly?

### ISSUE THREAD

**Issue by an0** [Kapeli/Dash-iOS#38]
The process of generating doc using Dash on macOS and then transferring to iOS devices using iTunes is tedious and time consuming.

I remember it can be done in the App Store version before it is removed from the App Store. So why it cannot be done now?

**Comment by Kapeli** [comment]
Apple requested that I stop distributing their docs. Sorry!

**Comment by scj643** [comment]
Would it be possible to scrape the docs from their website?

**Comment by Kapeli** [comment]
That would take a lot of time (and bandwidth) to do on the app's side.
