### ISSUE TITLE
Inside-Page Index Jumping doesn't work for Apple doc

### ISSUE THREAD

**Issue by an0** [Kapeli/Dash-iOS#39]
Nothing happens after tapping items in index.

![indexbug](https://cloud.githubusercontent.com/assets/100976/22792576/d7e40c1c-eeb2-11e6-8850-f79f2fb41f9a.gif)

**Comment by Kapeli** [comment]
How did you install the Apple API Reference docset?

**Comment by an0** [comment]
It is generated using Dash on macOS and then transferred to iOS devices using iTunes. 

All the used software are of the latest version(not beta). Dash iOS is newly pulled.

**Comment by Kapeli** [comment]
Thanks. I was able to fix the issue.

Do this on macOS:
1. Check for updates in Preferences > Downloads. This might seem like it does nothing, but it will silently grab the latest "Apple Docs Helper" command line tool
2. Regenerate the iOS-compatible docset from Preferences > Docsets
