### ISSUE TITLE
Instructions in README result in Debug build of app

### ISSUE THREAD

**Issue by e28eta** [Kapeli/Dash-iOS#42]
Following the readme instructions (and instructions on kapeli.com) results in a non-optimized, debug build of Dash for iOS. This isn't terrible, and anyone familiar with Xcode can fix it, but I think it'd be nice to improve the situation for everyone else.

I can think of two easy ways to solve this, and I'm not sure which you'd prefer. Obviously, the instructions could be edited to add step 6.5: change the build configuration.

It might be even better to check in a shared scheme that uses the Release configuration for the Run action. This has the potential to confuse existing users with the repo checked out (when they suddenly have two schemes: the autogenerated one and the shared one), and it introduces friction for anyone hacking on the codebase who expects the Run action to use the Debug config. I think those are reasonable tradeoffs to keep the instructions simpler for everyone else, but it's not obvious to me which is the right choice.

Thanks!

**Comment by Kapeli** [comment]
This is definitely something that would be nice to do, but since I don't really like the tradeoffs I must ask: is it something we must do? Have you noticed any performance improvements when running a release build rather than a debug build?

**Comment by e28eta** [comment]
Good question, I don't know. I'm only a causal user of the app and haven't tried the using Debug configuration for any period of time.

**Comment by Kapeli** [comment]
Going to close this, as Dash is now distributed on the App Store.
