### ISSUE TITLE
Some issues about the iOS API

### ISSUE THREAD

**Issue by jijiucheng** [Kapeli/Dash-iOS#43]
I also downloaded the file with type of ".docset" .And transporting into my iPhone following your offered method. However there is nothing when I open the "Apple API Reference".So that's why?

**Comment by Kapeli** [comment]
That happens when you don't convert the docset to iOS.

On the iOS app go to Settings > Main Docsets > Apple API Reference and follow the instructions.

**Comment by jijiucheng** [comment]
![111](https://cloud.githubusercontent.com/assets/15060707/23822200/f3d4c140-0682-11e7-89b2-cd56c6a8fc6e.png)
![222](https://cloud.githubusercontent.com/assets/15060707/23822201/f6d6befc-0682-11e7-894b-e90d2b253102.png)
![333](https://cloud.githubusercontent.com/assets/15060707/23822202/f8f525ca-0682-11e7-8b64-ce260dd531ed.png)

I also downloaded the file by mac and cover the docset, however there is nothing when I open the "Apple API Reference".I don't know that's why?

**Comment by jijiucheng** [comment]
There are some steps likes I do it when I go to Settings > Main Docsets > Apple API Reference and follow the instructions.

![444](https://cloud.githubusercontent.com/assets/15060707/23822251/6169c560-0684-11e7-954a-13045efbd565.png)
