### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Manloff** [Kapeli/Dash-iOS#44]
Hi, I use Dash for read ''Apple_API_Reference'', after I follow the prompts, I had transfer the .docset file to my iPhone, But When I click a className(or protocol, method...), Dash cannot load the data, the detail page shows "Page not found", my phone is iPhone6s, iOS version is 10.3.

**Comment by Kapeli** [comment]
Can you show me a screenshot?

**Comment by Huang-Libo** [comment]
![img_0654](https://cloud.githubusercontent.com/assets/12227130/24128529/73babf68-0e17-11e7-8dfa-5ba28706127d.png)

**Comment by Manloff** [comment]
I had reinstall the app, the file size is 1.65GB, I used almost 1h for transfer it, thank you
![190](https://cloud.githubusercontent.com/assets/12522976/24131817/d3adc19a-0e2b-11e7-859e-fdfd90164d68.gif)

**Comment by Kapeli** [comment]
@Huang-Libo: the `load?request_key` at the top means you haven't converted the docset. Follow the instructions in Settings > Main Docsets > Apple API Reference.

@Manloff: looks like the converted docset wasn't transferred properly. Try again.
