### ISSUE TITLE
Bug: Persistent Docsets Disappearing

### ISSUE THREAD

**Issue by Kautenja** [Kapeli/Dash-iOS#46]
Expected Behavior: docsets will download and persist between app restarts

Observed Behavior: docsets download and can be accessed, but when the app is terminated and restarted they disappear. 

Steps to reproduce: 

1.   install a docset

1.   terminate the application

1.   restart the app

1.   observe the docset list showing as empty

**Comment by Kapeli** [comment]
I'm not able to replicate this. How do you terminate the app?

Does it happen when you run the app in simulator or on device?

What iOS version are you using?

**Comment by Kautenja** [comment]
I'm running it on a physical iPhone 7 on iOS10.2. I terminate the app by double pressing the home button and swiping up on the apps view. I can't replicate the issue on a simulator either and I've actually started noticing this same issues in 2 other apps on my device so I now believe it is my device at fault.
