### ISSUE TITLE
Some cell is in the wrong section.

### ISSUE THREAD

**Issue by Huang-Libo** [Kapeli/Dash-iOS#47]
## Look at the picture below,  The `Class` cell should appear at _Class-Definition Data Structures_ section.

![img_0726](https://cloud.githubusercontent.com/assets/12227130/24650470/de7e5da0-195c-11e7-9c68-697bdef78e7f.png)

**Comment by Kapeli** [comment]
I've fixed this. Please reinstall the docset.
