### ISSUE TITLE
Apple API Reference can't open, show the error message on the navigation bar "load?request_key=hscYxNleEn"

### ISSUE THREAD

**Issue by caohrong** [Kapeli/Dash-iOS#49]
I used iTunes to transfer Apple API Reference to Dash.  I can open the document tree. But When I selected any Classes or Methods. On the navigation bar title is "load?request_key=hscYxNleEn" without any content on the screen. Anyone knows what's happening? Thanks.

**Comment by Kapeli** [comment]
That means you didn't convert the docset to iOS before transferring it. The Apple API Reference docset is a bit special and needs to be converted, unlike other docsets.

On Dash for iOS go to Settings > Main Docsets > Apple API Reference and follow the instructions.
