### ISSUE TITLE
Swift port

### ISSUE THREAD

**Issue by lfarah** [Kapeli/Dash-iOS#6]
I don't think that Dash became open source just so people can take a look at the code. I believe we can work together and bring new things to this amazing app a lot of people use.

One of the things that would open even more for the community to contribute would be a Swift port since we already have a large number of people who started iOS development in Swift and don't have enough knowledge in Objective-C to contribute.

By porting to Swift we're also making sure this code is ready for future features since a lot of new open source libraries are written in Swift, as well as specific Swift features that could reduce the complexity of the code.

Of course, this idea is kinda crazy because of the complexity of the whole project and the amount of code written here, but if we organize a team, I believe this can happen.

Any thoughts? 🤔

**Comment by Kapeli** [comment]
I personally don't like Swift's strictness and as long as Obj-C is an alternative, I'm going to use it. I wouldn't mind if someone made a Swift port, but I wouldn't be endorsing/contributing to it. Sorry!
