### ISSUE TITLE
Bug: Can't Delete Swift Docset

### ISSUE THREAD

**Issue by JustinJiaDev** [Kapeli/Dash-iOS#65]
Since `Swift` docset is removed, the settings page for the `Swift` docset displays the download button. Users previously downloaded `Swift` docset can no longer delete it.

**Comment by Kapeli** [comment]
Fixed in https://github.com/Kapeli/Dash-iOS/commit/ca9c9f64daf9eac30c4dcc000f99240a424bb123. Will be live in the next update.
