### ISSUE TITLE
Apple API Reference can't be transferred

### ISSUE THREAD

**Issue by mihaicris** [Kapeli/Dash-iOS#66]
Transferring with iTunes is completely broken. Tried with iMazing, the same, transfer speed is 0.01 MB/s
For a 2.46GB file size this is unusable.
Other means of transfer is absolutely needed otherwise the app is useless.
-> Import the file via Files app which can see the docset from iCloud or Dropbox or whatever.

Other solution upload to the app via a localhost web server like in many other apps.

I don't know but...this limitation in iTunes for transfering big files is ridiculous.

**Comment by aamck** [comment]
Just AirDrop it.

**Comment by mihaicris** [comment]
I can't pair my iPad Pro with my Mac. Don't know why.
I do find though to be a reasonable feature for this app.
Anyway, I am trying to implement this feature myself.
Wish me luck!

**Comment by Kapeli** [comment]
iTunes File Sharing in iOS 11 is broken for folders with a large number of files. The size itself isn't the issue.

I'm currently trying to get Dash for iOS to just generate the docs on the fly, like Dash for macOS does. This means that we'll be able to skip the docset converting part altogether and not have to generate the large number of files at all.

**Comment by jamesdbailey** [comment]
Airdrop doesn't stay connected. I get about 1/4 of the docset and then it auto-cancels.

**Comment by jamesdbailey** [comment]
maybe you could write/find unzip code.

**Comment by Kapeli** [comment]
This is almost done.

If anyone wants to help test it build Dash from master and transfer the "unconverted" Apple API Reference docset from Dash for macOS to it. To do this, go to Preferences > Docsets on Dash for macOS, right click the Apple API Reference docset and choose "Show in Finder". Transfer it to iOS using iTunes File Sharing or whatever.

**Comment by Kapeli** [comment]
@mihaicris I've turned this issue into "Apple API Reference can't be transferred".

If you want to open a new issue regarding Dash for iOS support for Files please do so.

**Comment by jamesdbailey** [comment]
Weird, I get an error: 'Apple_Docs_Framework/Apple_Docs_Framework.h' file not found. Yet the file is there and the framework appears to be linked correctly.

**Comment by Kapeli** [comment]
Should be fixed now. Sorry about that.

**Comment by mihaicris** [comment]
@Kapeli  I’ve tested and it works perfectly. Transfer is super fast and the conversion also. I checked randomly some classes and there are no missing links. For my initial feature request I consider it no longer needed. This is much better.
Thanks a lot for the fast fix.

**Comment by jamesdbailey** [comment]
Worked for me as well. The Apple Guides and Sample code is still very slow but it did work. The API Reference was much faster (and more important).

**Comment by Kapeli** [comment]
The Apple Guides and Sample Code docset has been removed since Xcode 9. It's no longer maintained.
