### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ClementPadovani** [Kapeli/Dash-iOS#67]
Hey,

Per your latest update, I'm getting a constant crash at launch (update and clean install).

Attached are the crash logs.

Configuration: iPhone X running iOS 11.2.1

(Compressed the .crash logs to please GitHub)
[Archive.zip](https://github.com/Kapeli/Dash-iOS/files/1621957/Archive.zip)

**Comment by Kapeli** [comment]
A fix has been submitted to the App Store and is waiting for review.
