### ISSUE TITLE
"Error: Unknown error encountered while generating HTML."

### ISSUE THREAD

**Issue by philosopherdog** [Kapeli/Dash-iOS#71]
I get this error on the latest app store version. I tried downloading the docsets by airdrop, itunes and ifunbox. I tried having the mac version generate the docset and I tried it without the docset generating. I only get the error on some entries. For instance "Collection" protocol and "Comparable" protocol. These seem to be in the Swift standard library documentation. Anyone else seeing this?

**Comment by Kapeli** [comment]
What version of Xcode is "xcode-select -p" pointing to on the Mac side?

**Comment by philosopherdog** [comment]
/Applications/Xcode.app/Contents/Developer

Xcode 9.2
Build version 9C40b

**Comment by Kapeli** [comment]
Can you archive the Apple_API_Reference.docset you're transferring to iOS and upload it somewhere?

**Comment by philosopherdog** [comment]
https://bitbucket.org/sthomps/docset

**Comment by Kapeli** [comment]
Should be fixed in master now. Please try it if you can.

**Comment by philosopherdog** [comment]
I just installed it and seems to be working now. Thanx.
