### ISSUE TITLE
Apple API Reference Guides Showing Anonymous

### ISSUE THREAD

**Issue by philosopherdog** [Kapeli/Dash-iOS#75]
I'm using the latest non-app store version. I dropped the docset onto the app without preparing it first. 

When I navigate to the guides, the first few pages are fine. After that I'm getting "Anonymous" as the title. So, it's not being parsed correctly. 

Here's an image: https://imgur.com/BxWwE2D

**Comment by Kapeli** [comment]
These are actual pages and their title is really "Anonymous". It's not really a parsing issue, just the way Apple organised the docs.

I've decided to remove these pages from the search index completely, as I think there's no point in having them.

To update your docset, check for updates in Dash for macOS and re-transfer the docset to iOS.
