### ISSUE TITLE
iPhoneX landscape UI issue

### ISSUE THREAD

**Issue by qinyuhang** [Kapeli/Dash-iOS#76]
Hi, I have experienced a issue using iPhoneX landscape. U see in the picture, the number in the list has a wrong position, which should be in the left side of the arrow, and this cause the number covered by the notch.
![image1](https://user-images.githubusercontent.com/6239057/37527564-47f69984-296d-11e8-938f-cf99da259d63.png)

**Comment by DmytriE** [comment]
How are you able to view the numbers?  Performing simulations on my computer and the new iPhoneX hides the sub-reference count value.  Unfortunately I don't have an iPhoneX to test on personally.
