### ISSUE TITLE
Question: dash-android

### ISSUE THREAD

**Issue by ArazAbishov** [Kapeli/Dash-iOS#85]
It could be nice to have an android client for Dash as well, and I would like to volunteer building it :)

I was wondering if the API of Dash is open to third-party developers, and if yes, where one can find docs / samples of how to consume it? 

Thanks!

**Comment by Kapeli** [comment]
Check out https://blog.kapeli.com/dash-for-ios-android-windows-or-linux. If you're interested, please email me.
