### ISSUE TITLE
iOS Dash doesn't accept Air Drop.

### ISSUE THREAD

**Issue by MasaruKitajima** [Kapeli/Dash-iOS#89]
Hi all,

I'm a Japanese and I'm running bot macOS Mojave and iOS 12 in Japanese.

When I tried to send my .dash file via AirDrop, a popup appeared on iOS with three options "AppStore", "File", "Reject."

I can't receive it by Dash for iOS.

Selecting "AppStore" brings me to AppStore, but dialogue pops up saying "This item can't be used in your country."

Selecting "File" brings me to File, but I can't find any Dash folder inside iPhone.

How can I share my own snippets to Dash for iOS?

**Comment by Kapeli** [comment]
Dash for iOS doesn't currently support snippets. See https://github.com/Kapeli/Dash-iOS/issues/74.

**Comment by MasaruKitajima** [comment]
Thanks.
